### ISSUE TITLE
bnode object URIs are not live links in HTML

### ISSUE THREAD

**Issue by briesenberg07** [UniverityOfWashingtonLibrariesSchemas/schemasProject#11]
I indicated previously that URIs in our output HTML table were not live links, asked you about this, and then looked again and saw that they actually were (or so I thought).  

Looking at the HTML today, I realized that while URIs occurring as objects of rdf:resource subjects are live links, URIs occurring as objects of blank nodes are not.  

I will look at the rdf2rdfa-v0-2-truncated transform to see whether I can determine how to fix this, but also wanted to pass this along to you to confirm.

**Comment by gerontakos** [comment]
That's a good catch, thank you. I'll fix it next week, after the pull.
