### ISSUE TITLE
SourceResource typo in landing pages

### ISSUE THREAD

**Issue by briesenberg07** [UniverityOfWashingtonLibrariesSchemas/schemasProject#13]
Need to correct spelling of SourceResource in UWSW landing pages.
It was thought that the problem would appear in an RDF2RDFa transform--perhaps in a variable--but the typo has not yet been found.
[BR](https://github.com/briesenberg07) will review.

**Comment by briesenberg07** [comment]
Also see [Asana task/subtasks](https://app.asana.com/0/1114594466853414/1116384057219061/f) for assorted landing page issues such as this one.

**Comment by briesenberg07** [comment]
@gerontakos 
I believe that the source of this typo is one triple in the RDF/XML document titled *University of Washington Libraries' Semantic Web Data* (download [here](https://www.lib.washington.edu/static/public/cams/data/datasets/uwSemWeb.rdf)) as follows:

`<rdf:Description rdf:about="https://doi.org/10.6069/uwlib.55.a.3.1">
    <dct:title xml:lang="en">Instances of the SourceResouce Class</dct:title>`

- [UWLSWD landing page](https://doi.org/10.6069/uwlib.55.a):
   - Under "This dataset consists of 6 partitions:"
      - &lt;ul&gt; --&gt; &lt;li&gt; element populates a link with hot text as follows:
      - `<a href="{distinct-values(key('resources',@rdf:resource)/@rdf:about[1])}">
                                <xsl:value-of select="key('resources', @rdf:resource)/dct:title"/>
                            </a>`
      - (the **xsl:key** element was a new one on me but I'm fairly sure that this is correct).
- [Instances of the SourceResouce Class](https://doi.org/10.6069/uwlib.55.A.3.1):
   - Includes `<xsl:variable name="usw" select="document('file:////Users/theodore/Desktop/ldStage/datasets/uwSemWeb.rdf')"/>`
   - &lt;h1&gt; element populates a title using this variable as follows: `<xsl:value-of select="$usw/rdf:RDF/rdf:Description[@rdf:about = $doi]/dct:title"/>`

So, ***action items*** would be:
- Find "authoritative version" of this RDF/XML document (or just download from the landing page)
- Fix typo
- Run the following two XSLT transformations again, with appropriate source files.
   - rdf2rdfa-uwSemWeb.xsl
   - rdf2rdfa-sourceResource.xsl

Is this correct?

**Comment by gerontakos** [comment]
Thank you for sleuthing this. We do have a labyrinthine data-grabbing process we should evaluate in some detail someday!
