### ISSUE TITLE
Most recent RDF2RDFa transforms available?

### ISSUE THREAD

**Issue by briesenberg07** [UniverityOfWashingtonLibrariesSchemas/schemasProject#14]
@gerontakos 
Looking through the XSLT files just now to find RDF2RDFa transforms that may need work (see issues #13 and #12), it isn't actually clear to me that the transforms used to produce current UWSW landing pages are posted in the repository. 
All RDF2RDFa transforms I see were created for a prior iteration of UWSW data, when design dictated that individual collections would have individual published datasets. They don't look like they could have been used to output current class-partition or UWSW landing pages. 
Am I missing something?

**Comment by gerontakos** [comment]
Quite right, these were never committed, but they are in my local git repo. I'll need to commit and push, hopefully today.

**Comment by briesenberg07** [comment]
I see your commit from March 24 (cc1984b68e0b1658d6519ab413861ea16f9bb296), I think I now have what I need--thank you!
