### ISSUE TITLE
briesenberg07 still doesn't have push access?

### ISSUE THREAD

**Issue by briesenberg07** [UniverityOfWashingtonLibrariesSchemas/schemasProject#18]
Hi @gerontakos \:

I believe that I still don't have push access to `schemasProject`. Could have sworn that we set this up, as I'll be working on a DD for the Sephardic Studies digital collection.

Please change permissions, or let me know if you've changed your mind about this.

Thanks!

![image](https://user-images.githubusercontent.com/27664966/97935360-3089c080-1d2d-11eb-8636-b342372d2219.png)

![image](https://user-images.githubusercontent.com/27664966/97935405-4f885280-1d2d-11eb-9309-b18f6a9370b2.png)

![image](https://user-images.githubusercontent.com/27664966/97935422-5b741480-1d2d-11eb-90f3-b11fd35cdc0f.png)

**Comment by gerontakos** [comment]
We did set this up but, obviously, incorrectly.

Try again, I just maximized your role, let's see if it works.

  --Theo

________________________________

**Comment by briesenberg07** [comment]
Thanks Theo, closing issue (belatedly)
