### ISSUE TITLE
Possible to transform three xml dds for output to HTML?

### ISSUE THREAD

**Issue by briesenberg07** [UniverityOfWashingtonLibrariesSchemas/schemasProject#22]
[Current scripting to output HTML](https://github.com/briesenberg07/libraryNotes/blob/master/xslt/dd2html_vertical_mig.xsl) uses an oXygen transformation scenario to process a single XML source file:

![image](https://user-images.githubusercontent.com/27664966/118592035-258efe80-b75a-11eb-9541-b5894d0954b2.png)

However I'm planning to use [three separate property lists](https://github.com/UniverityOfWashingtonLibrariesSchemas/schemasProject/commit/b8c0d881a689f2bf57f8ae95aeaac7952fac0e00) (three `data-dictionary.xml` files) to manage and present property sets for 1) textual resources 2) audio resources (songs) and 3) audio resources (oral histories).

If possible, I'd like to process all three XML docs for output to a single HTML doc which presents multiple property sets. 

I don't have a method for doing this at the top of my head\* and wondered whether @gerontakos might have any ideas for this within easy reach.

\* One vague idea is to create a single stylesheet which uses `fn:transform` to iterate over the multiple source docs in some way, perhaps using [multiple vars (`xsl:sequence` > `fn:transform`)](https://github.com/uwlib-cams/webviews/blob/f62d081f645bfaffd89b76644e9d948a23e0ed30/xslt/profiles-to-html5-all.xsl#L13-L25)...

**Comment by gerontakos** [comment]
There are ways to do this. I usually store a document in a variable using the document() function:
<xsl:variable name="doc3" select="document('path-to-document.xml')"/>
Your context will then be the document node and you can navigate the document using XPath as usual.
You can also use a key to perform specific lookups, designating the external document in the third argument of the key() function.
I don't know if there's a new shiny approach in XSLT 3. If you find something in 3.0, I'd be interested to hear.

**Comment by briesenberg07** [comment]
Thank you for the ideas @gerontakos !
I shall have to dive in a bit more and let you know what I come up with (or, as often happens, what trouble I run into). Thanks again ~

**Comment by briesenberg07** [comment]
Resolved with [this commit](https://github.com/briesenberg07/libraryNotes/commit/c5bb4f906f39d26a73fa98c86fbeee71a6e59c94) to **libraryNotes**, where I have the XSLT.  See [`fn:document()` in three variables](https://github.com/briesenberg07/libraryNotes/blob/c5bb4f906f39d26a73fa98c86fbeee71a6e59c94/xslt/ssdc_dd2html_vertical_mig.xsl#L36-L44) at top of the transform. Thanks again @gerontakos ! Having this transform in working order is a big load off and now I can focus on getting our two remaining property lists in order.

Calls to named templates are still repeated in code (for example, the same named template is called [here](https://github.com/briesenberg07/libraryNotes/blob/c5bb4f906f39d26a73fa98c86fbeee71a6e59c94/xslt/ssdc_dd2html_vertical_mig.xsl#L97-L107), [here](https://github.com/briesenberg07/libraryNotes/blob/c5bb4f906f39d26a73fa98c86fbeee71a6e59c94/xslt/ssdc_dd2html_vertical_mig.xsl#L138-L148), and [here](https://github.com/briesenberg07/libraryNotes/blob/c5bb4f906f39d26a73fa98c86fbeee71a6e59c94/xslt/ssdc_dd2html_vertical_mig.xsl#L180-L190) for each of the three document variables). I think this could be improved, but I don't know at the moment how to iterate over the three documents in some way to eliminate this.
