### ISSUE TITLE
Missing rdf:type properties?

### ISSUE THREAD

**Issue by briesenberg07** [UniverityOfWashingtonLibrariesSchemas/schemasProject#4]
## Web resource file
@gerontakos 
Currently, output web resources do not have any rdf:type property. 
(See webresource.rdf output from cdm-2-rdf.xsl.)
Should I add rdf:type = edm:WebResource to the transform (sub-template for web resource file) to provide this property/value for each web resource?

**Comment by briesenberg07** [comment]
## Aggregation file
As with output web resources file, currently output aggregations do not have any rdf:type properties. 
Add rdf:type = ore:aggregation?

**Comment by gerontakos** [comment]
Yes there should be types for both, thank you.

**Comment by briesenberg07** [comment]
Added to transform, see commit 245c5f1
